# -*- coding: utf-8 -*-
"""DigitImageClassificationDL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rsKaDhTMj6ty8y-kXSyEHk-oYj0vItL
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt
import numpy as np

#load datasets
(X_train,Y_train), (X_test,Y_test) = mnist.load_data()

#normalize images
X_train = X_train/255  #X_TRAIN IMAGE #Y_test -(0-9)
X_test = X_test/255

#build model
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dense(10,activation="softmax")
]
)

#compile
model.compile(
    optimizer = "adam",
    loss ="sparse_categorical_crossentropy",
    metrics =["accuracy"]
)

#train model'
model.fit(X_train,Y_train,epochs=5)

#predict
prediction = model.predict(X_test)

#show image with prediction
plt.imshow(X_test[543] , cmap="Blues")
plt.title("Predicted Digit:" +str(np.argmax(prediction[543])))

